[theme]
backgroundImage= "https://media.wired.com/photos/5c9ba67d1e34481170ef2bcd/191:100/w_1508,h_789,c_limit/Culture_Matrix_RedPillBluePill-1047403844.jpg"
primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"